export default {
  ADD_IMAGE: 'ADD_IMAGE',
  GET_IMAGE: 'GET_IMAGE',
  GET_IMAGES: 'GET_IMAGES',
  REMOVE_IMAGE: 'REMOVE_IMAGE',
  SET_CURRENT_IMAGE: 'SET_CURRENT_IMAGE',
  GET_CURRENT_IMAGE: 'GET_CURRENT_IMAGE',
  REMOVE_CURRENT_IMAGE: 'REMOVE_CURRENT_IMAGE',
  SET_APP: 'SET_APP',
  GET_APP: 'GET_APP',
}
